//
// Created by rudz on 6/9/16.
//

// Just for da lolz and complex control of radar :-)


#ifndef QR_RADAR2_CONTROLHEADERS_H
#define QR_RADAR2_CONTROLHEADERS_H

#define QR_CONTROL_NONE 0
#define QR_CONTROL_ALL 1
#define QR_CONTROL_LARGEST 10
#define QR_CONTROL_SMALLEST 20
#define QR_CONTROL_QUAD_1 30
#define QR_CONTROL_QUAD_2 40
#define QR_CONTROL_QUAD_3 50
#define QR_CONTROL_QUAD_4 60
#define QR_CONTROL_RIGHT 70
#define QR_CONTROL_LEFT 80
#define QR_CONTROL_UPPER 90
#define QR_CONTROL_LOWER 100

#define QR_CONTROL_MSG_OK "CONTROL SET OK"
#define QR_CONTROL_MSG_FAIL "CONTROL SET FAIL"

#endif //QR_RADAR2_CONTROLHEADERS_H
